from cpuinfo import get_cpu_info
import platform
import sys
import psutil
from dmidecode import DMIDecode

qemu_emulator_binaries = {
	"X86_64": "qemu-system-x86_64"
}

qemu_cpu_flags = [
	"3dnow",
	"3dnowext",
	"3dnowprefetch",
	"abm",
	"ace2",
	"ace2-en",
	"acpi",
	"adx",
	"aes",
	"amd-no-ssb",
	"amd-ssbd",
	"amd-stibp",
	"apic",
	"arat",
	"arch-capabilities",
	"avx",
	"avx2",
	"avx512-4fmaps",
	"avx512-4vnniw",
	"avx512-bf16",
	"avx512-vp2intersect",
	"avx512-vpopcntdq",
	"avx512bitalg",
	"avx512bw",
	"avx512cd",
	"avx512dq",
	"avx512er",
	"avx512f",
	"avx512ifma",
	"avx512pf",
	"avx512vbmi",
	"avx512vbmi2",
	"avx512vl",
	"avx512vnni",
	"bmi1",
	"bmi2",
	"cid",
	"cldemote",
	"clflush",
	"clflushopt",
	"clwb",
	"clzero",
	"cmov",
	"cmp-legacy",
	"core-capability",
	"cr8legacy",
	"cx16",
	"cx8",
	"dca",
	"de",
	"decodeassists",
	"ds",
	"ds-cpl",
	"dtes64",
	"erms",
	"est",
	"extapic",
	"f16c",
	"flushbyasid",
	"fma",
	"fma4",
	"fpu",
	"fsgsbase",
	"fsrm",
	"full-width-write",
	"fxsr",
	"fxsr-opt",
	"gfni",
	"hle",
	"ht",
	"hypervisor",
	"ia64",
	"ibpb",
	"ibrs-all",
	"ibs",
	"intel-pt",
	"invpcid",
	"invtsc",
	"kvm-asyncpf",
	"kvm-asyncpf-int",
	"kvm-hint-dedicated",
	"kvm-mmu",
	"kvm-nopiodelay",
	"kvm-poll-control",
	"kvm-pv-eoi",
	"kvm-pv-ipi",
	"kvm-pv-sched-yield",
	"kvm-pv-tlb-flush",
	"kvm-pv-unhalt",
	"kvm-steal-time",
	"kvmclock",
	"kvmclock",
	"kvmclock-stable-bit",
	"la57",
	"lahf-lm",
	"lbrv",
	"lm",
	"lwp",
	"mca",
	"mce",
	"md-clear",
	"mds-no",
	"misalignsse",
	"mmx",
	"mmxext",
	"monitor",
	"movbe",
	"movdir64b",
	"movdiri",
	"mpx",
	"msr",
	"mtrr",
	"nodeid-msr",
	"npt",
	"nrip-save",
	"nx",
	"osvw",
	"pae",
	"pat",
	"pause-filter",
	"pbe",
	"pcid",
	"pclmulqdq",
	"pcommit",
	"pdcm",
	"pdpe1gb",
	"perfctr-core",
	"perfctr-nb",
	"pfthreshold",
	"pge",
	"phe",
	"phe-en",
	"pku",
	"pmm",
	"pmm-en",
	"pn",
	"pni",
	"popcnt",
	"pschange-mc-no",
	"pse",
	"pse36",
	"rdctl-no",
	"rdpid",
	"rdrand",
	"rdseed",
	"rdtscp",
	"rsba",
	"rtm",
	"sep",
	"serialize",
	"sha-ni",
	"skinit",
	"skip-l1dfl-vmentry",
	"smap",
	"smep",
	"smx",
	"spec-ctrl",
	"split-lock-detect",
	"ss",
	"ssb-no",
	"ssbd",
	"sse",
	"sse2",
	"sse4.1",
	"sse4.2",
	"sse4a",
	"ssse3",
	"stibp",
	"svm",
	"svm-lock",
	"syscall",
	"taa-no",
	"tbm",
	"tce",
	"tm",
	"tm2",
	"topoext",
	"tsc",
	"tsc-adjust",
	"tsc-deadline",
	"tsc-scale",
	"tsx-ctrl",
	"tsx-ldtrk",
	"umip",
	"vaes",
	"virt-ssbd",
	"vmcb-clean",
	"vme",
	"vmx",
	"vmx-activity-hlt",
	"vmx-activity-shutdown",
	"vmx-activity-wait-sipi",
	"vmx-apicv-register",
	"vmx-apicv-vid",
	"vmx-apicv-x2apic",
	"vmx-apicv-xapic",
	"vmx-cr3-load-noexit",
	"vmx-cr3-store-noexit",
	"vmx-cr8-load-exit",
	"vmx-cr8-store-exit",
	"vmx-desc-exit",
	"vmx-encls-exit",
	"vmx-entry-ia32e-mode",
	"vmx-entry-load-bndcfgs",
	"vmx-entry-load-efer",
	"vmx-entry-load-pat",
	"vmx-entry-load-perf-global-ctrl",
	"vmx-entry-load-rtit-ctl",
	"vmx-entry-noload-debugctl",
	"vmx-ept",
	"vmx-ept-1gb",
	"vmx-ept-2mb",
	"vmx-ept-advanced-exitinfo",
	"vmx-ept-execonly",
	"vmx-eptad",
	"vmx-eptp-switching",
	"vmx-exit-ack-intr",
	"vmx-exit-clear-bndcfgs",
	"vmx-exit-clear-rtit-ctl",
	"vmx-exit-load-efer",
	"vmx-exit-load-pat",
	"vmx-exit-load-perf-global-ctrl",
	"vmx-exit-nosave-debugctl",
	"vmx-exit-save-efer",
	"vmx-exit-save-pat",
	"vmx-exit-save-preemption-timer",
	"vmx-flexpriority",
	"vmx-hlt-exit",
	"vmx-ins-outs",
	"vmx-intr-exit",
	"vmx-invept",
	"vmx-invept-all-context",
	"vmx-invept-single-context",
	"vmx-invept-single-context",
	"vmx-invept-single-context-noglobals",
	"vmx-invlpg-exit",
	"vmx-invpcid-exit",
	"vmx-invvpid",
	"vmx-invvpid-all-context",
	"vmx-invvpid-single-addr",
	"vmx-io-bitmap",
	"vmx-io-exit",
	"vmx-monitor-exit",
	"vmx-movdr-exit",
	"vmx-msr-bitmap",
	"vmx-mtf",
	"vmx-mwait-exit",
	"vmx-nmi-exit",
	"vmx-page-walk-4",
	"vmx-page-walk-5",
	"vmx-pause-exit",
	"vmx-ple",
	"vmx-pml",
	"vmx-posted-intr",
	"vmx-preemption-timer",
	"vmx-rdpmc-exit",
	"vmx-rdrand-exit",
	"vmx-rdseed-exit",
	"vmx-rdtsc-exit",
	"vmx-rdtscp-exit",
	"vmx-secondary-ctls",
	"vmx-shadow-vmcs",
	"vmx-store-lma",
	"vmx-true-ctls",
	"vmx-tsc-offset",
	"vmx-unrestricted-guest",
	"vmx-vintr-pending",
	"vmx-vmfunc",
	"vmx-vmwrite-vmexit-fields",
	"vmx-vnmi",
	"vmx-vnmi-pending",
	"vmx-vpid",
	"vmx-wbinvd-exit",
	"vmx-xsaves",
	"vmx-zero-len-inject",
	"vpclmulqdq",
	"waitpkg",
	"wbnoinvd",
	"wdt",
	"x2apic",
	"xcrypt",
	"xcrypt-en",
	"xgetbv1",
	"xop",
	"xsave",
	"xsavec",
	"xsaveerptr",
	"xsaveopt",
	"xsaves",
	"xstore",
	"xstore-en",
	"xtpr"
]

if __name__ == '__main__':    

	# Query CPU
	cpuinfo = get_cpu_info()

	# Determine qemu binary
	if not cpuinfo["arch"] in qemu_emulator_binaries:
		sys.exit("Architecture not recognized")
	else:
		print(qemu_emulator_binaries[cpuinfo["arch"]], "\\")

	# Determine CPU
	cpu = "    -cpu qemu64"

	# Determine CPU flags
	for flag in cpuinfo["flags"]:
		if flag in qemu_cpu_flags:
			cpu += ",+"
			cpu += flag

	print(cpu, "\\")

	# Run dmidecode
	dmi = DMIDecode()

	# Type 0 (BIOS)
	for data in filter(lambda x: x["DMIType"] == 0, dmi.data.values()):
		print("    -smbios 'type=0,vendor={0},version={1},date={2}' \\".format(data["Vendor"], data["Version"], data["Release Date"]))

	# Type 1 (System)
	for data in filter(lambda x: x["DMIType"] == 1, dmi.data.values()):
		print("    -smbios 'type=1,manufacturer={0},product={1},version={2},serial={3},uuid={4},sku={5},family={6}' \\".format(data["Manufacturer"], data["Product Name"], data["Version"], data["Serial Number"], data["UUID"], data["SKU Number"], data["Family"]))

	# Type 2 (Baseboard)
	for data in filter(lambda x: x["DMIType"] == 2, dmi.data.values()):
		print("    -smbios 'type=2,manufacturer={0},product={1},version={2},serial={3},asset={4},location={5}' \\".format(data["Manufacturer"], data["Product Name"], data["Version"], data["Serial Number"], data["Asset Tag"], data["Location In Chassis"]))

	# Type 3 (Chassis)
	# Type 4 (Processor)
	# Type 11 (OEM Strings)
	# Type 17 (Memory Device)

	# 

	# Output memory
	print("    -m", psutil.virtual_memory().total / 1e6)

	sys.exit(0)
